### ISSUE TITLE
It isn't recognizing my files

### ISSUE THREAD

**Issue by alexandresgf** [brandonwamboldt/sublime-nginx#12]
Hi,

I just downloaded the compressed file into the user's folder in Browse Packages, but nothing happen. It isn't recognizing my *.conf files. Do I need to uncompress the file or do something more?

Thanks!

**Comment by abou7mied** [comment]
Yes you should uncompress them

![image](https://cloud.githubusercontent.com/assets/3378281/20605419/054cec76-b274-11e6-9b6f-588d369b8d10.png)

**Comment by alexandresgf** [comment]
Thanks!
