### ISSUE TITLE
comments syntax highlighting

### ISSUE THREAD

**Issue by plentz** [brandonwamboldt/sublime-nginx#4]
There's a problem with nginx conf files where comments sometimes isn't proper highlighted. If ou look here https://gist.github.com/plentz/6737338#file-nginx-conf-L6-L9 some comments aren't displayed in grey.

related: https://github.com/github/linguist/issues/2155

**Comment by plentz** [comment]
nevermind :)

**Comment by brandonwamboldt** [comment]
well ok then :)

**Comment by brandonwamboldt** [comment]
Thanks for reporting this as it prompted me to look into the issue and it turns out it was a bug which is now fixed :smile:

**Comment by plentz** [comment]
@brandonwamboldt <3
